accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signup_view, name='signup'),
    path('success/',views.success,name='success'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('board/', views.create_board, name='create_board'),
    path('create_pin/', views.create_pin, name='create_pin'),
    path('dashboard/pin/<int:id>/', views.pin_detail_view, name='pin'),
]

pinterest/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



# def user_directory_path(instance, filename):
#     return "user_{0}/{1}".format(instance.user.id, filename)


class CustomUser(AbstractUser):
    date_of_birth = models.DateField()









class Board(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


        
class Pin(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    catagory = models.CharField(max_length=255)  # Assuming you have a separate Tag model
    image = models.ImageField(upload_to='pins/')  # Image upload field
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title            

    

accounts/forms.py
# from django import forms
# from .models import UserProfile

# class SignupForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['username', 'password', 'date_of_birth']
#         widgets = {
#             'password': forms.PasswordInput()
#         }

from django import forms
from .models import CustomUser, Board , Pin

class SignupForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password', 'date_of_birth']
        widgets = {
            'password': forms.PasswordInput(),
        }

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name']

class PinForm(forms.ModelForm):
    class Meta:
        model = Pin
        fields = ['board', 'title', 'catagory', 'image', 'description']

accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import login, authenticate,logout
from .forms import SignupForm
from .models import CustomUser
from .forms import BoardForm, PinForm
from .models import Board, Pin
from django.contrib.auth.decorators import login_required


def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            # Create a new user account
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            date_of_birth = form.cleaned_data['date_of_birth']

            # Create the user with an encrypted password
            user = CustomUser(username=username, date_of_birth=date_of_birth)
            user.set_password(password)  # Set the encrypted password
            user.save()
            
            # Authenticate the user and log them in
            user = authenticate(request, username=username, password=password)
            login(request, user)
            
            return redirect('dashboard')  
    else:
        form = SignupForm()
    
    return render(request, 'signup.html', {'form': form})

def success(request):
    return render(request, 'success.html')

@login_required
def dashboard_view(request):
    username = request.user.username  
    pins = Pin.objects.all()
    context = {'pins': pins ,'username': username}
    return render(request, 'dashboard.html', context)  


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')  
        else:
            error_message = 'Invalid username or password'  
            print(error_message)
            return render(request, 'signup.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')


@login_required
def logout_view(request):
    logout(request)
    return redirect('signup')



# dashboard page views

@login_required
def create_board(request):
    if request.method == 'POST':
        board_form = BoardForm(request.POST)
        if board_form.is_valid():
            board = board_form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('dashboard')
    else:
        board_form = BoardForm()

    context = {
        'form': board_form,
    }
    return render(request, 'create_board.html', context)



# create pin view

@login_required
def create_pin(request):
    if request.method == 'POST':
        pin_form = PinForm(request.POST, request.FILES)
        if pin_form.is_valid():
            pin = pin_form.save(commit=False)
            print(request.POST)
            pin.board = get_board_object(request)  
            pin.save()
            return redirect('dashboard')
    else:
        pin_form = PinForm()

    context = {
        'pin_form': pin_form,
    }
    return render(request, 'create_pin.html', context)

def get_board_object(request):
    board_id = request.POST.get('board') 
    board = get_object_or_404(Board, id=board_id)
    return board

def pin_detail_view(request, id):
    pin_detail = Pin.objects.select_related('board__user').get(id=id)
    host = pin_detail.board.user.username

    context = {
        'pin_detail': pin_detail,
        'host' : host
    }
    return render(request, 'pin_detail.html', context)

accounts/templates/create_board.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Create Board</title>
  <style>
    /* styles.css */
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      padding: 0;
      background-color: #f0f0f0;
    }

    .card {
      width: 400px;
      padding: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    h2 {
      text-align: center;
    }

    form {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .form-input {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      border: none;
      border-radius: 5px;
      background-color: #f0f0f0;
    }

    .form-submit {
      width: fit-content;
      padding: 10px;
      background-color: #e60023;
      color: #fff;
      font-size: 16px;
      font-weight: bold;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }

    .form-submit:hover {
      background-color: #c4001a;
    }
  </style>
</head>

<body>
  <div class="card">
    <h2>Create a New Board</h2>
    <form method="post">
      {% csrf_token %}
      <input class="form-input" type="text" name="name" placeholder="Board Name" required>
      <button class="form-submit" type="submit">Create</button>
    </form>
  </div>
</body>

</html>

 
 

accounts/templates/create_pin.html
<!-- create_pin.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Create Pin</title>
  <style>
    /* styles.css */
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      padding: 0;
      background-color: #f0f0f0;
    }

    .pin-form-container {
      width: 600px;
      padding: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .pin-form-section {
      padding-right: 20px;
      display: flex;
      margin-bottom: 20px;
    }

    .pin-form-section .left-section {
      flex: 1;
      padding-right: 20px;
      border-right: 1px solid #ccc;
    }

    .pin-form-section .right-section {
      flex: 1;
      padding-left: 20px;
    }

    .pin-form-title {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 20px;
    }

    .pin-form-input {
      width: 100%;
      padding: 10px;
      margin-bottom: 10px;
      border: none;
      border-radius: 5px;
      background-color: #f0f0f0;
    }

    .pin-form-submit {
      width: fit-content;
      padding: 10px;
      background-color: #e60023;
      color: #fff;
      font-size: 16px;
      font-weight: bold;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      margin-left: auto; /* Add this CSS to move the button to the right */
    }

    .pin-form-submit:hover {
      background-color: #c4001a;
    }
  </style>
</head>
<body>


  

  <div class="pin-form-container">
    <h1 class="pin-form-title">Create Pin Here</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="pin-form-section">
        <div class="left-section">
          {{ pin_form.image }}
          <!-- Add drag and drop box here if desired -->
        </div>

        <div class="right-section">
          <label for="">Board</label>
          <select id="board-select" class="pin-form-input" name="{{ pin_form.board.name }}">
            {% for choice in pin_form.board.field.widget.choices %}
              <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
          </select>
          <br>

          <input class="pin-form-input" type="text" name="{{ pin_form.title.name }}" placeholder="Title">
          <br>

          <input class="pin-form-input" type="text" name="{{ pin_form.catagory.name }}" placeholder="Category">
          <br>
        </div>
      </div>

      <div class="pin-form-section">
        <div class="left-section"></div>

        <div class="right-section">
          <textarea class="pin-form-input" name="{{ pin_form.description.name }}" placeholder="Description"></textarea>
          <br>
        </div>
      </div>

      <div class="pin-form-section">
        <div class="left-section"></div>

        <div class="right-section">
          <button class="pin-form-submit" type="submit">Save</button>
        </div>
      </div>
    </form>
  </div>
</body>
</html>

accounts/templates/create_pin_modal.html
<style>
  .modal-overlay {
    display: block;
  }

  .modal-container {
    display: block;
  }

  .modal-content {
    background-color: yellow;
    margin: 10% auto;
    padding: 20px;
    border-radius: 10%;
    background-color: white;
    margin: 10% auto;
    border-radius: 100%;
    border: 2px solid red;
    padding: 2rem;
    border-radius: 8px;
    width: 80%;
    width: 60vw;
    margin-left: 20%;
    z-index: 5;
  }

  .form-container {
    display: flex;
    align-items: flex-start;
  }

  .left-section {
    flex: 1;
  }

  .image-upload {
    /* height:47vh; */
    border: 2px dashed #ddd;
    border-radius: 8px;
    padding: 20px;
    text-align: center;
  }

  .image-upload label {
    font-size: 16px;
    color: #888;
    margin-bottom: 10px;
  }

  .image-upload input[type="file"] {
    display: none;
  }

  .image-upload::before {
    content: "+";
    display: block;
    font-size: 40px;
    color: #bbb;
    margin-bottom: 10px;
  }

  .image-preview {
    max-width: 100%;
    max-height: 200px;
    /* Adjust the maximum height as needed */
    margin-bottom: 10px;
    display: none;
  }

  .right-section {
    flex: 1;
    padding-left: 20px;
  }

  .form-fields label {
    font-size: 16px;
    font-weight: bold;
    color: #333;
    margin-bottom: 5px;
  }

  .form-fields select,
  .form-fields input[type="text"],
  .form-fields textarea {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
    margin-bottom: 15px;
  }

  .form-fields textarea {
    height: 80px;
    resize: vertical;
  }

  .save-button {
    background-color: #bd081c;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
  }
</style>

<body>
  <!-- <a href="#" id="open-modal">Open Modal</a> -->

  <div class="modal-overlay"></div>
<div class="modal-container">
  <div class="modal-content" style="display: none;">
    <h1>This is Create Pin Page</h1>
    <div class="form-container">
      <div class="left-section">
        <div class="image-upload">
          <label for="id_image">Drag and drop or select an image:</label>
          <input type="file" id="id_image" name="image" accept="image/*">
          <img id="image-preview" class="image-preview" src="#" alt="Image Preview">
        </div>
      </div>
      <div class="right-section">
        <div class="form-fields">
          <label for="id_board">Board:</label>
          <select id="id_board" name="board">
            <option value="board1">Board 1</option>
            <option value="board2">Board 2</option>
            <option value="board3">Board 3</option>
          </select>

          <label for="id_title">Title:</label>
          <input type="text" id="id_title" name="title">

          <label for="id_category">Category:</label>
          <select id="id_category" name="category">
            <option value="category1">Category 1</option>
            <option value="category2">Category 2</option>
            <option value="category3">Category 3</option>
          </select>

          <label for="id_description">Description:</label>
          <textarea id="id_description" name="description"></textarea>
        </div>

        <button type="submit" class="save-button">Save</button>
      </div>
    </div>
  </div>
</div>


  <script>
    document.addEventListener("DOMContentLoaded", function (event) {
      var modalOverlay = document.querySelector('.modal-overlay');
      var modalContainer = document.querySelector('.modal-container');
      var modalContent = document.querySelector('.modal-content');

      modalOverlay.addEventListener('click', () => {
        modalOverlay.style.display = 'none';
        modalContainer.style.display = 'none';
        modalContent.style.display = 'none';
      });

      document.getElementById("image-input").addEventListener("change", function (event) {
        var reader = new FileReader();
        reader.onload = function () {
          var imagePreview = document.getElementById("image-preview");
          imagePreview.src = reader.result;
          imagePreview.style.display = "block";
        };
        reader.readAsDataURL(event.target.files[0]);
      });

      // Optional: Trigger the modal display on page load
      modalOverlay.style.display = 'block';
      modalContainer.style.display = 'block';
      modalContent.style.display = 'block';
    });
  </script>

accounts/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/dashboard-nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard-card-layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard-user-dropdown.css' %}">

    <style>
        .pin:hover {
            box-shadow: 0 0 0 5px rgb(233, 142, 142);
        }
    </style>

</head>

<body>

    <!-- navbar start -->
    <nav class="navbar">
        <div class="navbar-logo">
            <a href="#"><i class="fa fa-brands fa-pinterest navbar-logo"
                    style="font-size: 1.7rem; margin-right: 0.5rem;"></i></a>
        </div>
        <ul class="navbar-links">
            <li><a href="#">Home</a></li>
            <li><a href="#">Explore</a></li>
            <li><a href="{% url 'create_pin' %}" id="">Create Pin</a></li>
            <li><a href="{% url 'create_board' %}" id="">Create Board</a></li>
        </ul>
        <div class="navbar-search">
            <input type="text" placeholder="Search">
            <button type="submit"><i class="fas fa-search"></i></button>
        </div>
        <ul class="navbar-icons">
            <li><a href="#"><i class="fas fa-bell"></i></a></li>
            <li><a href="#"><i class="fas fa-envelope"></i></a></li>
            <i class="fas fa-user user-icon" onclick="toggleMenu(event)"></i>
        </ul>

        <!-- navbar end -->


        <!-- user menu -->
        <div class="user-menu-container" id="user-menu-container">
            <ul class="menu">
                <li>{{username}}</li>
                <li><a href="{% url 'logout' %}">Logout</a></li>

            </ul>
        </div>
        <!-- user menu end -->

    </nav>



    <!-- pin container start -->

    <div class="pin_container">
        {% for pin in pins %}

        <div class="card {% cycle 'card_small' 'card_medium' 'card_large' %}">
            <a href="{% url 'pin' pin.id %}">
                <img class="pin" src="{{ pin.image.url }}" style="cursor: zoom-in;" alt="Pin Image">
            </a>
        </div>

        {% endfor %}
    </div>

    <!-- pin container end -->



</body>
<script src="{% static 'js/dashboard-user-dropdown.js' %}"></script>




</html>

accounts/templates/pin_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>pin details html</h1>
    <h2>{{pin_detail.id}}</h2>
    <h2>{{pin_detail.board_id}}</h2>
    <h2>{{pin_detail.title}}</h2>
    <h2>{{pin_detail.description}}</h2>
    <h2>{{pin_detail.created_at}}</h2>
    <h2>{{pin_detail.updated_at}}</h2>


    <img src="{{pin_detail.image.url}}" alt="">
    <h2>{{host}}</h2>
</body>
</html>

accounts/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pinterest - India</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>



    <nav class="navbar">
        <a href="#" class="logo"><i class="fa fa-brands fa-pinterest card-logo"
                style="font-size: 1.7rem; margin-right: 0.5rem;"></i>Pinterest</a>
        <ul class="nav-links">
            <li><a href="#">About</a></li>
            <li><a href="#">Business</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#" class="login" id="loginLink">Login</a></li>
            <li><a href="#" class="signup" id="signupLink">Signup</a></li>
        </ul>
    </nav>

    <img src="https://i.ibb.co/9qhnWB9/Screenshot-2023-06-23-at-3-46-08-PM.png"
        width="100%" alt="">

    <div id="signupCard" class="card hidden">
        <div class="card-body">
            <i class="fa fa-brands fa-pinterest card-logo" style="font-size: 40px;"></i>
            <i class="fa-solid fa-xmark cut-icon" id="close-form-btn-signup" style="font-size: 1.5rem;"></i>
            <h3 class="card-title">Welcome to Pinterest</h3>
            <p>Find new ideas to try</p>

            <form id="signupForm" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Email address</label>
                    <input type="text" id="id_username" name="{{ form.username.name }}" placeholder="Email address"
                        class="form-control">
                    <div id="usernameError" class="error-message"></div>
                </div>
                <div class="form-group">
                    <label for="id_password">Password</label>
                    <input type="password" id="id_password" name="{{ form.password.name }}"
                        placeholder="Create a password" class="form-control">
                    <div id="passwordError" class="error-message"></div>
                    <i class="fa far fa-eye" id="togglePassword"></i>
                </div>

                <div class="form-group">
                    <label for="id_date_of_birth">Date of birth</label>
                    <input type="date" id="id_date_of_birth" name="{{ form.date_of_birth.name }}"
                        value="{{ form.date_of_birth.value|date:'Y-m-d' }}" class="form-control">
                    <div id="dateOfBirthError" class="error-message"></div>
                </div>
                <button type="submit" class="btn btn-primary signup-button">Continue</button>
            </form>
        </div>
    </div>


    <div id="loginCard" class="card hidden">
        <div class="card-body">
            <i class="fa fa-brands fa-pinterest card-logo" style="font-size: 40px;"></i>
            <i class="fa-solid fa-xmark cut-icon" id="close-form-btn-login" style="font-size: 1.5rem;"></i>
            <h3 class="card-title">Welcome to Pinterest</h3>
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Email address</label>
                    <input type="text" id="username" name="username" placeholder="Email" required><br>

                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="id_password_login" name="password" placeholder="Password" required><br>
                    <i class="fa far fa-eye" id="togglePasswordLogin"></i>
                    <div id="invalidLoginDetails" class="error-message" style="margin-top: 20px;"></div>
                </div>
                
                <button type="submit" class="btn btn-primary" style="margin-top: 3rem;">Log in </button>
            </form>
        </div>
    </div>



</body>

{% if error_message %}
<script>
    var errorMessage = "{{ error_message }}";
    document.getElementById("loginCard").classList.remove("hidden");

    var invalidLoginDetails = document.getElementById('invalidLoginDetails');
    // event.preventDefault();  // Prevent form submission
    invalidLoginDetails.textContent = errorMessage;
</script>
{% endif %}
<script src="{% static 'js/index.js' %}"></script>

</html>

accounts/templates/success.html
<h1> This is success page</h1>